# Database-only backup configuration
# Uses different repository path to avoid conflicts

# Add VM backup directory for database dumps and VictoriaMetrics snapshots
source_directories:
  - /tmp/vm-backup

repositories:
  - path: /mnt/nas-direct/backups/server-databases

read_special: true

keep_daily: 7
keep_weekly: 4
keep_monthly: 12
keep_yearly: 1

postgresql_databases:
  - name: immich_photos
    hostname: localhost
    port: 5432
    username: immich_photos_user
    password: "{credential file /home/server/backup/credentials/immich-db-password.txt}"
    format: custom
    options: "--no-owner --no-privileges"
    pg_dump_command: docker exec immich_postgres pg_dump
    pg_restore_command: docker exec immich_postgres pg_restore
    psql_command: docker exec immich_postgres psql

sqlite_databases:
  - name: vaultwarden
    path: /home/server/vaultwarden/vw-data/db.sqlite3
  - name: kleio
    path: /home/server/kleio_data/kleio.db
  - name: ntfy_auth
    path: /home/server/ntfy/data/auth.db
  - name: ntfy_cache
    path: /home/server/ntfy/data/cache.db
  - name: grafana
    path: /var/lib/docker/volumes/monitoring_grafana_data/_data/grafana.db
  - name: drone
    path: /home/server/drone/var/lib/drone/database.sqlite
  - name: jellyfin_library
    path: /home/server/jellyfin/config/data/library.db
  - name: jellyfin_main
    path: /home/server/jellyfin/config/data/jellyfin.db
  - name: filebrowser
    path: /home/server/files/filebrowser-db/filebrowser.db

commands:
  - before: action
    when: [create]
    run:
      - curl -X POST http://localhost:8428/snapshot/create
      - mkdir -p /tmp/vm-backup
      - docker cp victoriametrics:/victoria-metrics-data/snapshots /tmp/vm-backup/
  - after: action
    when: [create]
    run:
      - 'echo "borgmatic_backup_success{config=\"databases\"} 1" > /var/lib/node_exporter/textfile_collector/borgmatic_databases.prom'
      - 'echo "borgmatic_backup_last_run_timestamp $(date +%s)" >> /var/lib/node_exporter/textfile_collector/borgmatic_databases.prom'
      - rm -rf /tmp/vm-backup
      - curl -X POST http://localhost:8428/snapshot/delete_all
  - after: error
    run:
      - 'echo "borgmatic_backup_success{config=\"databases\"} 0" > /var/lib/node_exporter/textfile_collector/borgmatic_databases.prom'
      - 'echo "borgmatic_backup_last_run_timestamp $(date +%s)" >> /var/lib/node_exporter/textfile_collector/borgmatic_databases.prom'