source_directories:
  - /home
  - /etc
  - /var/log
  - /var/lib
  - /opt
  - /tmp/vm-backup

exclude_patterns:
  - /home/*/.cache
  - /home/*/.local/share/Trash
  - /home/*/snap/*/common/.cache
  - /var/cache
  - /var/tmp
  - /var/log/journal
  - '*.tmp'
  - '*.log.*'
  - '__pycache__'
  - node_modules
  - .git/objects
  - .npm
  - .yarn/cache
  # SQLite WAL and shared memory files that can cause locks
  - '*.sqlite-wal'
  - '*.sqlite3-wal'
  - '*.sqlite-shm' 
  - '*.sqlite3-shm'
  # Docker overlay filesystem and special device files
  - '/var/lib/docker/overlay2'
  - '/var/lib/docker/volumes/*/backingFsBlockDev'

repositories:
  - path: /mnt/nas-direct/backups/server

read_special: true

keep_daily: 7
keep_weekly: 4
keep_monthly: 12
keep_yearly: 1

postgresql_databases:
  - name: immich_photos
    hostname: localhost
    port: 5432
    username: immich_photos_user
    password: "{credential file /home/server/backup/credentials/immich-db-password.txt}"
    format: custom
    options: "--no-owner --no-privileges"
    pg_dump_command: docker exec immich_postgres pg_dump
    pg_restore_command: docker exec immich_postgres pg_restore
    psql_command: docker exec immich_postgres psql
  - name: all
    hostname: localhost
    port: 5432
    username: postgres
    password: "{credential file /home/server/backup/credentials/postgres-admin-password.txt}"
    format: custom
    options: "--no-owner --no-privileges"
    pg_dump_command: docker exec postgres18 pg_dumpall
    pg_restore_command: docker exec postgres18 psql
    psql_command: docker exec postgres18 psql

# Using file-level backup instead of database dumps to avoid WAL lock issues
# sqlite_databases:
#   - name: vaultwarden
#     path: /home/server/vaultwarden/vw-data/db.sqlite3

commands:
  - before: action
    when: [create]
    run:
      - curl -X POST http://localhost:8428/snapshot/create
      - mkdir -p /tmp/vm-backup
      - docker cp victoriametrics:/victoria-metrics-data/snapshots /tmp/vm-backup/
  - after: action
    when: [create]
    run:
      - rm -rf /tmp/vm-backup
      - curl -X POST http://localhost:8428/snapshot/delete_all

# Disabled ZFS snapshots due to Docker overlay filesystem conflicts
# zfs:
