services:
  kopia:
    image: kopia/kopia:latest
    hostname: backup-server
    container_name: kopia
    restart: unless-stopped
    user: root
    ports:
      - "51515:51515"
    command:
      - server
      - start
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=admin
      - --server-password=${KOPIA_SERVER_PASSWORD}
      - --override-hostname=backup-server
    environment:
      KOPIA_PASSWORD: ${KOPIA_REPO_PASSWORD}
      USER: "server"
      TZ: "America/Chicago"
    volumes:
      - ./config:/app/config
      - ./cache:/app/cache
      - ./logs:/app/logs
      - /mnt/nas-direct/backups:/repository
      - /home/server:/data/home:ro
      - /var/lib/docker/volumes:/data/docker-volumes:ro
      - /etc:/data/etc:ro
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      # HTTP UI route
      - "traefik.http.routers.kopia-ui.rule=Host(`server.bobparsons.dev`)"
      - "traefik.http.routers.kopia-ui.entrypoints=https"
      - "traefik.http.routers.kopia-ui.tls.certresolver=letsencrypt"
      - "traefik.http.services.kopia-ui.loadbalancer.server.port=51515"
      # GRPC route
      - "traefik.http.routers.kopia-grpc.rule=Host(`server.bobparsons.dev`) && Headers(`content-type`, `application/grpc`)"
      - "traefik.http.routers.kopia-grpc.entrypoints=https"
      - "traefik.http.routers.kopia-grpc.tls.certresolver=letsencrypt"
      - "traefik.http.services.kopia-grpc.loadbalancer.server.port=51515"
      - "traefik.http.services.kopia-grpc.loadbalancer.server.scheme=h2c"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
      - kopia

networks:
  traefik:
    external: true
  kopia:
    driver: bridge
